name: C Workflow

on:
  push:
    branches: ["main"]
    tags:
      - '*'
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: make setup
      - name: Run Linter
        run: make lint
      - name: Run Tests
        run: make test
      - name: Run Compiler
        run: make
      - name: Run Valgrind
        continue-on-error: true
        run: make check
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/${{ github.event.repository.name }}
          asset_name: ${{ github.event.repository.name }}-linux-amd64
          tag: ${{ github.ref }}

